version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.3.0

jobs:
  test:
    docker:
      - image: circleci/buildpack-deps:14.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: test
          command: docker-compose run --rm app rspec
      - run:
          name: lint
          command: docker-compose run --rm app rubocop

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_DEFAULT_REGION
          repo: "formbuilder/fb-pdf-generator"
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only: master
