version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.3.0

jobs:
  test:
    docker:
      - image: circleci/buildpack-deps:14.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: test
          command: docker-compose run --rm app rspec
      - run:
          name: lint
          command: docker-compose run --rm app rubocop
  deploy_to_test:
    working_directory: ~/circle/git/fb-pdf-generator
    docker:
      - image: asmega/fb-builder:latest
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "b4:5d:52:af:b2:58:87:f9:ae:f3:4b:1f:32:9f:91:d7"
      - run:
          name: deploy to test dev
          command: './deploy/scripts/circle_deploy.sh $CIRCLE_SHA1 "test-dev" $KUBE_TOKEN_TEST_DEV'
      - run:
          name: deploy to test staging
          command: './deploy/scripts/circle_deploy.sh $CIRCLE_SHA1 "test-staging" $KUBE_TOKEN_TEST_STAGING'
      - run:
          name: deploy to test production
          command: './deploy/scripts/circle_deploy.sh $CIRCLE_SHA1 "test-production" $KUBE_TOKEN_TEST_PRODUCTION'

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          name: build_test_image
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_DEFAULT_REGION
          repo: "formbuilder/fb-pdf-generator"
          tag: "${CIRCLE_SHA1}"
          # filters:
          #   branches:
          #     only: master
      - deploy_to_test:
          requires:
            - test
            - build_test_image
