version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.3.0

commands:
  checkout-git-crypt:
    description: "Downloads decrypts secrets using git crypt"
    parameters:
      repo-url:
        type: env_var_name
        default: GIT_CRYPT_SSH_REPO_URL
        description: 'git ssh url to clone i.e git@github.com:<MY-ORG>/<MY-REPO>.git'
      git-crypt-key:
        type: env_var_name
        default: ENCODED_GIT_CRYPT_KEY
        description: 'base64 encoded decryption key'
      repo-clone-directroy:
        type: string
        default: deploy-config
    steps:
      - run:
          name: Clone secrets repo
          command: |
            GIT_SSH_COMMAND='ssh -v -i << parameters.ssh-key >> -o "IdentitiesOnly=yes"' git clone ${<< parameters.repo-url >>} << parameters.repo-clone-directroy >>
      - run:
          name: Decrypt secrets
          command: |
            cd deploy-config
            git-crypt unlock <( echo ${<< parameters.git-crypt-key >>} | base64 -d)

jobs:
  test:
    docker:
      - image: circleci/buildpack-deps:14.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: test
          command: docker-compose run --rm app rspec
      - run:
          name: lint
          command: docker-compose run --rm app rubocop
  deploy_to_test:
    working_directory: ~/circle/git/fb-pdf-generator
    docker:
      - image: asmega/fb-builder:latest
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "b4:5d:52:af:b2:58:87:f9:ae:f3:4b:1f:32:9f:91:d7"
      - checkout-git-crypt
      - run:
          name: deploy to test dev
          command: './deploy/scripts/circle_deploy.sh $CIRCLE_SHA1 "test-dev" $KUBE_TOKEN_TEST_DEV'
      - run:
          name: deploy to test staging
          command: './deploy/scripts/circle_deploy.sh $CIRCLE_SHA1 "test-staging" $KUBE_TOKEN_TEST_STAGING'
      - run:
          name: deploy to test production
          command: './deploy/scripts/circle_deploy.sh $CIRCLE_SHA1 "test-production" $KUBE_TOKEN_TEST_PRODUCTION'

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          name: build_test_image
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_DEFAULT_REGION
          repo: "formbuilder/fb-pdf-generator"
          tag: "${CIRCLE_SHA1}"
          # filters:
          #   branches:
          #     only: master
      - deploy_to_test:
          requires:
            - test
            - build_test_image
